final List<String> frases = [
  'Vejo nos seus olhos seu jeito de amar, vejo no seu jeito o prazer de te amar.',
  'Se o amor é pecado, jamais serei inocente, pois jurei a mim mesmo, amar-te eternamente!',
  'Amar é sofrer um instante de saudade, é sentir um segundo de ciúmes, viver um momento de paixão.',
  'Eu te amo tanto que cada amanhecer é um novo encanto, lírio puro e santo, que planto por querer.',
  'Amo-te tanto que se um dia eu te perder na dor do desencanto, silenciarei meu canto e não saberei mais viver.',
  'A importância da vida não é ser importante. O importante é ser especial e você é.',
  'Fui ver o que era felicidade no dicionário, mas a definição estava errada. Deveria constar o seu nome.',
  'Se meu coração partisse, eu te dava um pedacinho, mas como ele não parte, te dou ele inteirinho.',
  'Tudo que sonhei um dia encontrar está resumido em uma só palavra: você !',
  'Se meus versos revelassem tudo que eu sentisse, talvez contassem coisas que nunca disse.',
  'Te Amo, não somente pelo que és, mas pelo que sou quando estou contigo!',
  'O amor é o maior e melhor sentimento que duas pessoas podem compartilhar.',
  'Há pessoas que passam por nossa vida e levam um pouco de nós na lembrança e há pessoas que simplesmente ficam, como você.',
  'Se a tua vida depender do meu amor, viverás além da vida, pois lhe amo além do amor.',
  'Tudo na vida passa, mas de repente, você ficou na minha eternamente!',
  'Palavras podem não dizer o que o coração sente, mas fazem sentir o que o coração diz.',
  'Quando duas pessoas realmente se gostam, elas sempre darão um jeito de dar certo. Não importa o quão difícil seja.',
  'Que o amor seja a melhor forma de começar e terminar o dia.',
  'Te amo. Com todas as letras, palavras e pronúncias. Em todas as línguas e sotaques. Em todos os sentidos e jeitos. Com todas as circunstâncias e motivos. Simplesmente, te amo.',
  'O plano é bem simples: ficar com você a minha vida inteira.',
  'Eu amo estar com você, eu amo ficar com você, seu cheirinho me faz viajar, sua voz me faz suspirar.',
  'Até o infinito fica pequeno quando se trata do que eu sinto por você. Te amo muito!',
  'Um dia alguém vai te abraçar tão apertado que todas suas peças quebradas irão se juntar novamente.',
  'Para nós, todo o amor do mundo.',
  'Se o sol não voltar amanhã, eu uso o seu sorriso pra iluminar o meu dia.',
  'Porque em cada pedaço de mim, sempre haverá um pedaço de você.',
  'Se eu tivesse que escolher entre te amar ou respirar, eu usaria meu último suspiro pra dizer: eu te amo!',
  'O amor verdadeiro não tem final feliz. O amor verdadeiro não tem final.',
  'Sozinho, sou prosa. Ao teu lado, poesia.',
  'Eu andei por ai guardando todo esse amor pra te dar. Que bom que ele é seu, que bom que é você.',
  'Se amar é viver, vivo porque amo você.',
  'Você é tudo que eu preciso!',
  'Te amarei até o meu último átomo.',
  'A dois, a tempestade é linda!',
  'Que seja eterno como todo grande amor devia ser. E se não for, que seja ao menos terno. E se não for, que seja ao menos amor.',
  'Se você quiser alguém para ser só seu, é só não esquecer que eu estarei aqui.',
  'A vontade de te ver já é maior que tudo!',
  'Espero pelo seu sorriso como a noite espera pelas estrelas.',
  'Se a vida acabasse hoje ou daqui mil anos, eu escolheria você.',
  'Assim como viver sem ter amor não é viver, não há você sem mim, eu não existo sem você.',
];